// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using NVDFeedImporter;
//
//    var feedVulnerabilities = FeedVulnerabilities.FromJson(jsonString);

using System;
using System.Globalization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace NVDFeedImporter
{
    using J = JsonPropertyAttribute;
    using R = Required;
    using N = NullValueHandling;

    public partial class FeedVulnerabilities
    {
        [J("cve", NullValueHandling = N.Ignore)]
        public Cve Cve { get; set; }

        [J("configurations", NullValueHandling = N.Ignore)]
        public Configurations Configurations { get; set; }

        [J("impact", NullValueHandling = N.Ignore)]
        public Impact Impact { get; set; }

        [J("publishedDate", NullValueHandling = N.Ignore)]
        public string PublishedDate { get; set; }

        [J("lastModifiedDate", NullValueHandling = N.Ignore)]
        public string LastModifiedDate { get; set; }
    }

    public class Configurations
    {
        [J("CVE_data_version", NullValueHandling = N.Ignore)]
        public string CveDataVersion { get; set; }

        [J("nodes", NullValueHandling = N.Ignore)]
        public Node[] Nodes { get; set; }
    }

    public class Node
    {
        [J("operator", NullValueHandling = N.Ignore)]
        public string Operator { get; set; }

        [J("cpe_match", NullValueHandling = N.Ignore)]
        public CpeMatch[] CpeMatch { get; set; }

        [J("children", NullValueHandling = N.Ignore)]
        public Child[] Children { get; set; }
    }

    public class Child
    {
        [J("operator", NullValueHandling = N.Ignore)]
        public string Operator { get; set; }

        [J("cpe_match", NullValueHandling = N.Ignore)]
        public CpeMatch[] CpeMatch { get; set; }
    }

    public class CpeMatch
    {
        [J("vulnerable", NullValueHandling = N.Ignore)]
        public bool? Vulnerable { get; set; }

        [J("cpe23Uri", NullValueHandling = N.Ignore)]
        public string Cpe23Uri { get; set; }

        [J("versionStartIncluding", NullValueHandling = N.Ignore)]
        public string VersionStartIncluding { get; set; }

        [J("versionEndIncluding", NullValueHandling = N.Ignore)]
        public string VersionEndIncluding { get; set; }

        [J("versionEndExcluding", NullValueHandling = N.Ignore)]
        public string VersionEndExcluding { get; set; }
    }

    public class Cve
    {
        [J("data_type", NullValueHandling = N.Ignore)]
        public string DataType { get; set; }

        [J("data_format", NullValueHandling = N.Ignore)]
        public string DataFormat { get; set; }

        [J("data_version", NullValueHandling = N.Ignore)]
        public string DataVersion { get; set; }

        [J("CVE_data_meta", NullValueHandling = N.Ignore)]
        public CveDataMeta CveDataMeta { get; set; }

        [J("problemtype", NullValueHandling = N.Ignore)]
        public Problemtype Problemtype { get; set; }

        [J("references", NullValueHandling = N.Ignore)]
        public References References { get; set; }

        [J("description", NullValueHandling = N.Ignore)]
        public CveDescription Description { get; set; }
    }

    public class CveDataMeta
    {
        [J("ID", NullValueHandling = N.Ignore)]
        public string Id { get; set; }

        [J("ASSIGNER", NullValueHandling = N.Ignore)]
        public string Assigner { get; set; }
    }

    public class CveDescription
    {
        [J("description_data", NullValueHandling = N.Ignore)]
        public DescriptionDatumElement[] DescriptionData { get; set; }
    }

    public class DescriptionDatumElement
    {
        [J("lang", NullValueHandling = N.Ignore)]
        public string Lang { get; set; }

        [J("value", NullValueHandling = N.Ignore)]
        public string Value { get; set; }
    }

    public class Problemtype
    {
        [J("problemtype_data", NullValueHandling = N.Ignore)]
        public ProblemtypeDatum[] ProblemtypeData { get; set; }
    }

    public class ProblemtypeDatum
    {
        [J("description", NullValueHandling = N.Ignore)]
        public DescriptionDatumElement[] Description { get; set; }
    }

    public class References
    {
        [J("reference_data", NullValueHandling = N.Ignore)]
        public ReferenceDatum[] ReferenceData { get; set; }
    }

    public class ReferenceDatum
    {
        [J("url", NullValueHandling = N.Ignore)]
        public Uri Url { get; set; }

        [J("name", NullValueHandling = N.Ignore)]
        public string Name { get; set; }

        [J("refsource", NullValueHandling = N.Ignore)]
        public string Refsource { get; set; }

        [J("tags", NullValueHandling = N.Ignore)]
        public string[] Tags { get; set; }
    }

    public class Impact
    {
        [J("baseMetricV3", NullValueHandling = N.Ignore)]
        public BaseMetricV3 BaseMetricV3 { get; set; }

        [J("baseMetricV2", NullValueHandling = N.Ignore)]
        public BaseMetricV2 BaseMetricV2 { get; set; }
    }

    public class BaseMetricV2
    {
        [J("cvssV2", NullValueHandling = N.Ignore)]
        public CvssV2 CvssV2 { get; set; }

        [J("severity", NullValueHandling = N.Ignore)]
        public string Severity { get; set; }

        [J("exploitabilityScore", NullValueHandling = N.Ignore)]
        public double? ExploitabilityScore { get; set; }

        [J("impactScore", NullValueHandling = N.Ignore)]
        public double? ImpactScore { get; set; }

        [J("acInsufInfo", NullValueHandling = N.Ignore)]
        public bool? AcInsufInfo { get; set; }

        [J("obtainAllPrivilege", NullValueHandling = N.Ignore)]
        public bool? ObtainAllPrivilege { get; set; }

        [J("obtainUserPrivilege", NullValueHandling = N.Ignore)]
        public bool? ObtainUserPrivilege { get; set; }

        [J("obtainOtherPrivilege", NullValueHandling = N.Ignore)]
        public bool? ObtainOtherPrivilege { get; set; }

        [J("userInteractionRequired", NullValueHandling = N.Ignore)]
        public bool? UserInteractionRequired { get; set; }
    }

    public class CvssV2
    {
        [J("version", NullValueHandling = N.Ignore)]
        public string Version { get; set; }

        [J("vectorString", NullValueHandling = N.Ignore)]
        public string VectorString { get; set; }

        [J("accessVector", NullValueHandling = N.Ignore)]
        public string AccessVector { get; set; }

        [J("accessComplexity", NullValueHandling = N.Ignore)]
        public string AccessComplexity { get; set; }

        [J("authentication", NullValueHandling = N.Ignore)]
        public string Authentication { get; set; }

        [J("confidentialityImpact", NullValueHandling = N.Ignore)]
        public string ConfidentialityImpact { get; set; }

        [J("integrityImpact", NullValueHandling = N.Ignore)]
        public string IntegrityImpact { get; set; }

        [J("availabilityImpact", NullValueHandling = N.Ignore)]
        public string AvailabilityImpact { get; set; }

        [J("baseScore", NullValueHandling = N.Ignore)]
        public double? BaseScore { get; set; }
    }

    public class BaseMetricV3
    {
        [J("cvssV3", NullValueHandling = N.Ignore)]
        public CvssV3 CvssV3 { get; set; }

        [J("exploitabilityScore", NullValueHandling = N.Ignore)]
        public double? ExploitabilityScore { get; set; }

        [J("impactScore", NullValueHandling = N.Ignore)]
        public double? ImpactScore { get; set; }
    }
    
    public enum AccessVectorType
    {
        LOCAL,
        NETWORK,
        ADJACENT_NETWORK,
        PHYSICAL,
        UNSPECIFIED
    }

    public class CvssV3
    {
        [J("version", NullValueHandling = N.Ignore)]
        public string Version { get; set; }

        [J("vectorString", NullValueHandling = N.Ignore)]
        public string VectorString { get; set; }

        [J("attackVector", NullValueHandling = N.Ignore)]
        public AccessVectorType AttackVector { get; set; }

        [J("attackComplexity", NullValueHandling = N.Ignore)]
        public string AttackComplexity { get; set; }

        [J("privilegesRequired", NullValueHandling = N.Ignore)]
        public string PrivilegesRequired { get; set; }

        [J("userInteraction", NullValueHandling = N.Ignore)]
        public string UserInteraction { get; set; }

        [J("scope", NullValueHandling = N.Ignore)]
        public string Scope { get; set; }

        [J("confidentialityImpact", NullValueHandling = N.Ignore)]
        public string ConfidentialityImpact { get; set; }

        [J("integrityImpact", NullValueHandling = N.Ignore)]
        public string IntegrityImpact { get; set; }

        [J("availabilityImpact", NullValueHandling = N.Ignore)]
        public string AvailabilityImpact { get; set; }

        [J("baseScore", NullValueHandling = N.Ignore)]
        public double? BaseScore { get; set; }

        [J("baseSeverity", NullValueHandling = N.Ignore)]
        public string BaseSeverity { get; set; }
    }

    public partial class FeedVulnerabilities
    {
        public static FeedVulnerabilities[] FromJson(string json)
        {
            return JsonConvert.DeserializeObject<FeedVulnerabilities[]>(json, Converter.Settings);
        }
    }

    public static class Serialize
    {
        public static string ToJson(this FeedVulnerabilities[] self)
        {
            return JsonConvert.SerializeObject(self, Converter.Settings);
        }
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter {DateTimeStyles = DateTimeStyles.AssumeUniversal}
            }
        };
    }
}